name: 01 ARO Landing Zone Continuous Integration

on:
  pull_request:
    branches: [main]
    paths:
      - 'terraform/**'
      - '.github/workflows/**'

permissions:
  contents: read
  id-token: write
  security-events: write

concurrency:
  group: aro-ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  CI:
    uses: ./.github/workflows/ci-template.yml
    with:
      environment: plan
      runner_label: ubuntu-latest
      working_directory: terraform
    secrets: inherit
